version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:17"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 3
    groups:
      verified-github-actions:
        patterns:
          - "*"
