from __future__ import annotations

from typing import Any

from .business_commercial_router import BusinessCommercialRouter

_COMMERCIAL_ROUTER = BusinessCommercialRouter()


class SoftwareEngineerAutonomyOperationsRouter:
    """Polish/English GUI routing for B71-B79 operations."""

    READ_PHRASES = (
        "status wykonania odzyskiwania", "historia wykonania odzyskiwania",
        "status b71", "recovery execution status",
        "status uczenia napraw", "historia uczenia napraw", "status b72",
        "recovery learning status",
        "centrum sterowania autonomią", "centrum sterowania autonomia",
        "status centrum sterowania", "status b73", "status b71-b79",
        "unified autonomy control center",
        "status globalnego watchdoga", "historia globalnego watchdoga",
        "status watchdoga autonomii", "status b74", "global watchdog status",
        "status bezpiecznego wdrożenia", "status bezpiecznego wdrozenia",
        "historia bezpiecznych wdrożeń", "historia bezpiecznych wdrozen",
        "status b75", "safe autonomous deployment status",
        "status menedżera wydań", "status menedzera wydan",
        "historia release train", "status b76", "autonomous release manager status",
        "status pamięci rozwoju", "status pamieci rozwoju",
        "historia pamięci rozwoju", "historia pamieci rozwoju",
        "status b77", "development memory status",
        "status bezpieczeństwa autonomii", "status bezpieczenstwa autonomii",
        "historia audytu bezpieczeństwa", "historia audytu bezpieczenstwa",
        "status b78", "security hardening status",
        "status produkcyjnej autonomii", "status autonomii produkcyjnej",
        "raport dzienny autonomii", "historia produkcyjnej autonomii",
        "status b79", "production autonomy status",
        "status business edition", "status business", "status b80",
        "licencja business edition", "status licencji business edition",
        "pokaż licencję business edition", "pokaz licencje business edition",
        "integralność business edition", "integralnosc business edition",
        "status integralności business edition",
        "status integralnosci business edition",
        "konfiguracja business edition", "konfiguracja business",
        "pokaż status business edition", "pokaz status business edition",
        "pokaż konfigurację business edition",
        "pokaz konfiguracje business edition",
        "business edition status", "business edition configuration",
        "business edition license", "business edition integrity",
        "status profili organizacji", "pokaż profile organizacji",
        "pokaz profile organizacji", "status b81",
        "organization profiles status",
        "status platformy licencyjnej", "status licencji b82",
        "status b82", "business license platform status",
        "status ról i uprawnień", "status rol i uprawnien",
        "status kontroli dostępu", "status kontroli dostepu",
        "status b83", "business access control status",
        "status platformy biznesowej", "status b81-b83",
        "business platform status",
        "status centrum audytu", "status audytu biznesowego", "status b84",
        "business audit center status",
        "status disaster recovery", "status checkpointów", "status checkpointow",
        "zweryfikuj ostatni checkpoint", "status b85",
        "business disaster recovery status",
        "status centrum aktualizacji", "skanuj pakiety aktualizacji",
        "status b86", "business update center status",
        "status operacji biznesowych", "status b84-b86",
        "business operations status",
        "status instalatora business edition", "status b87",
        "business installation manager status",
        "status release candidate rc1", "status rc1", "status b88",
        "zweryfikuj release candidate rc1", "verify release candidate",
        "business release candidate status",
        "status wdrożenia business", "status b87-b88",
        "business release status",
    )

    MUTATING_PHRASES = (
        "wykonaj zatwierdzony plan odzyskiwania",
        "zweryfikuj wykonanie odzyskiwania",
        "wycofaj ostatnie wykonanie odzyskiwania",
        "przeprowadź cykl uczenia napraw", "przeprowadz cykl uczenia napraw",
        "uruchom uczenie napraw", "zatrzymaj uczenie napraw",
        "wstrzymaj uczenie napraw", "wznów uczenie napraw", "wznow uczenie napraw",
        "uruchom centrum sterowania autonomią",
        "uruchom centrum sterowania autonomia",
        "zatrzymaj centrum sterowania autonomią",
        "zatrzymaj centrum sterowania autonomia",
        "wstrzymaj centrum sterowania autonomią",
        "wstrzymaj centrum sterowania autonomia",
        "wznów centrum sterowania autonomią",
        "wznow centrum sterowania autonomia",
        "uruchom bezpiecznych nadzorców", "uruchom bezpiecznych nadzorcow",
        "zatrzymaj wszystkie nadzorcy", "zatrzymaj wszystkich nadzorców",
        "zatrzymaj wszystkich nadzorcow",
        "wstrzymaj wszystkie nadzorcy", "wstrzymaj wszystkich nadzorców",
        "wstrzymaj wszystkich nadzorcow",
        "wznów bezpiecznych nadzorców", "wznow bezpiecznych nadzorcow",
        "przeprowadź skan watchdoga", "przeprowadz skan watchdoga",
        "uruchom globalny watchdog", "zatrzymaj globalny watchdog",
        "wstrzymaj globalny watchdog", "wznów globalny watchdog",
        "wznow globalny watchdog",
        "utwórz kandydat wdrożenia", "utworz kandydat wdrozenia",
        "uruchom canary wdrożenia", "uruchom canary wdrozenia",
        "promuj bezpieczne wdrożenie", "promuj bezpieczne wdrozenie",
        "wycofaj bezpieczne wdrożenie", "wycofaj bezpieczne wdrozenie",
        "utwórz release train", "utworz release train",
        "oznacz wydanie jako stabilne",
        "zapisz pamięć rozwoju", "zapisz pamiec rozwoju",
        "przeprowadź audyt bezpieczeństwa", "przeprowadz audyt bezpieczenstwa",
        "zastosuj bezpieczne utwardzenie",
        "uruchom produkcyjną autonomię 24/7", "uruchom produkcyjna autonomie 24/7",
        "zatrzymaj produkcyjną autonomię 24/7", "zatrzymaj produkcyjna autonomie 24/7",
        "wstrzymaj produkcyjną autonomię 24/7", "wstrzymaj produkcyjna autonomie 24/7",
        "wznów produkcyjną autonomię 24/7", "wznow produkcyjna autonomie 24/7",
        "przeprowadź cykl produkcyjnej autonomii",
        "przeprowadz cykl produkcyjnej autonomii",
        "execute approved recovery plan", "run recovery learning cycle",
        "start recovery learning", "stop recovery learning",
        "start safe autonomy supervisors", "stop all autonomy supervisors",
        "run global watchdog scan", "start global watchdog", "stop global watchdog",
        "create deployment candidate", "run deployment canary",
        "promote safe deployment", "rollback safe deployment",
        "create release train", "mark release stable",
        "capture development memory", "run security hardening audit",
        "apply safe security hardening", "start production autonomy 24x7",
        "stop production autonomy 24x7", "run production autonomy cycle",
        "utwórz profil organizacji", "utworz profil organizacji",
        "eksportuj profil organizacji",
        "uruchom trial licencji", "uruchom trial 14 dni",
        "eksportuj wniosek aktywacyjny",
        "dezaktywuj licencję business", "dezaktywuj licencje business",
        "ustaw rolę owner", "ustaw role owner",
        "ustaw rolę admin", "ustaw role admin",
        "ustaw rolę operator", "ustaw role operator",
        "ustaw rolę auditor", "ustaw role auditor",
        "create organization profile", "export organization profile",
        "start business license trial", "export license activation request",
        "eksportuj raport audytu", "export audit report",
        "utwórz checkpoint business edition", "utworz checkpoint business edition",
        "create business checkpoint",
        "przygotuj pakiet przywracania", "export restore package",
        "przygotuj aktualizację business edition",
        "przygotuj aktualizacje business edition", "stage business update",
        "eksportuj instalator aktualizacji", "export update installer",
        "inicjalizuj pierwsze uruchomienie business edition",
        "initialize business first run",
        "eksportuj instalator business edition", "export business setup package",
        "eksportuj bezpieczny deinstalator", "export safe business uninstaller",
        "eksportuj release candidate rc1", "eksportuj rc1",
        "export release candidate",
    )

    @classmethod
    def can_handle(cls, command: str) -> bool:
        normalized = " ".join(str(command).casefold().split())
        return _COMMERCIAL_ROUTER.can_handle(normalized) or any(
            phrase in normalized
            for phrase in cls.READ_PHRASES + cls.MUTATING_PHRASES
        )

    def try_handle(
        self,
        suite: Any,
        *,
        command: str,
        operation: str = "",
    ) -> dict[str, Any] | None:
        normalized = " ".join(str(command).casefold().split())
        commercial = _COMMERCIAL_ROUTER.try_handle(suite, command=normalized, operation=operation)
        if commercial is not None:
            return commercial
        action = self._action(operation, normalized)
        if action is None:
            return None
        service, method = self._target(suite, action)
        if service is None or not callable(getattr(service, method, None)):
            return {
                "success": False,
                "status": "AUTONOMY_OPERATIONS_SERVICE_UNAVAILABLE",
                "operation": "autonomy_governance_suite",
                "stage": action[:3].upper(),
                "errors": [f"Brak usługi dla operacji {action}."],
            }
        return getattr(service, method)()

    @classmethod
    def _action(cls, operation: str, normalized: str) -> str | None:
        checks = (
            ("b71_execute", ("wykonaj zatwierdzony plan odzyskiwania", "execute approved recovery plan")),
            ("b71_verify", ("zweryfikuj wykonanie odzyskiwania",)),
            ("b71_rollback", ("wycofaj ostatnie wykonanie odzyskiwania",)),
            ("b71_history", ("historia wykonania odzyskiwania",)),
            ("b71_status", ("status wykonania odzyskiwania", "status b71", "recovery execution status")),
            ("b72_cycle", ("cykl uczenia napraw", "run recovery learning cycle")),
            ("b72_start", ("uruchom uczenie napraw", "start recovery learning")),
            ("b72_stop", ("zatrzymaj uczenie napraw", "stop recovery learning")),
            ("b72_pause", ("wstrzymaj uczenie napraw",)),
            ("b72_resume", ("wznów uczenie napraw", "wznow uczenie napraw")),
            ("b72_history", ("historia uczenia napraw",)),
            ("b72_status", ("status uczenia napraw", "status b72", "recovery learning status")),
            ("b73_start", (
                "uruchom centrum sterowania autonomią",
                "uruchom centrum sterowania autonomia",
                "uruchom bezpiecznych nadzorców",
                "uruchom bezpiecznych nadzorcow",
                "start safe autonomy supervisors",
            )),
            ("b73_stop", (
                "zatrzymaj centrum sterowania autonomią",
                "zatrzymaj centrum sterowania autonomia",
                "zatrzymaj wszystkich nadzorców",
                "zatrzymaj wszystkich nadzorcow",
                "stop all autonomy supervisors",
            )),
            ("b73_pause", (
                "wstrzymaj centrum sterowania autonomią",
                "wstrzymaj centrum sterowania autonomia",
                "wstrzymaj wszystkich nadzorców",
                "wstrzymaj wszystkich nadzorcow",
            )),
            ("b73_resume", (
                "wznów centrum sterowania autonomią",
                "wznow centrum sterowania autonomia",
                "wznów bezpiecznych nadzorców",
                "wznow bezpiecznych nadzorcow",
            )),
            ("b73_history", ("historia centrum sterowania",)),
            ("b73_status", ("centrum sterowania autonomią", "centrum sterowania autonomia", "status centrum sterowania", "status b73", "status b71-b79", "unified autonomy control center")),
            ("b74_scan", ("skan watchdoga", "run global watchdog scan")),
            ("b74_start", ("uruchom globalny watchdog", "start global watchdog")),
            ("b74_stop", ("zatrzymaj globalny watchdog", "stop global watchdog")),
            ("b74_pause", ("wstrzymaj globalny watchdog",)),
            ("b74_resume", ("wznów globalny watchdog", "wznow globalny watchdog")),
            ("b74_history", ("historia globalnego watchdoga",)),
            ("b74_status", ("status globalnego watchdoga", "status watchdoga autonomii", "status b74", "global watchdog status")),
            ("b75_create", ("kandydat wdrożenia", "kandydat wdrozenia", "create deployment candidate")),
            ("b75_canary", ("canary wdrożenia", "canary wdrozenia", "run deployment canary")),
            ("b75_promote", ("promuj bezpieczne wdrożenie", "promuj bezpieczne wdrozenie", "promote safe deployment")),
            ("b75_rollback", ("wycofaj bezpieczne wdrożenie", "wycofaj bezpieczne wdrozenie", "rollback safe deployment")),
            ("b75_history", ("historia bezpiecznych wdrożeń", "historia bezpiecznych wdrozen")),
            ("b75_status", ("status bezpiecznego wdrożenia", "status bezpiecznego wdrozenia", "status b75", "safe autonomous deployment status")),
            ("b76_create", ("utwórz release train", "utworz release train", "create release train")),
            ("b76_stable", ("oznacz wydanie jako stabilne", "mark release stable")),
            ("b76_history", ("historia release train",)),
            ("b76_status", ("status menedżera wydań", "status menedzera wydan", "status b76", "autonomous release manager status")),
            ("b77_capture", ("zapisz pamięć rozwoju", "zapisz pamiec rozwoju", "capture development memory")),
            ("b77_history", ("historia pamięci rozwoju", "historia pamieci rozwoju")),
            ("b77_status", ("status pamięci rozwoju", "status pamieci rozwoju", "status b77", "development memory status")),
            ("b78_audit", ("audyt bezpieczeństwa", "audyt bezpieczenstwa", "run security hardening audit")),
            ("b78_harden", ("zastosuj bezpieczne utwardzenie", "apply safe security hardening")),
            ("b78_history", ("historia audytu bezpieczeństwa", "historia audytu bezpieczenstwa")),
            ("b78_status", ("status bezpieczeństwa autonomii", "status bezpieczenstwa autonomii", "status b78", "security hardening status")),
            ("b79_start", ("uruchom produkcyjną autonomię 24/7", "uruchom produkcyjna autonomie 24/7", "start production autonomy 24x7")),
            ("b79_stop", ("zatrzymaj produkcyjną autonomię 24/7", "zatrzymaj produkcyjna autonomie 24/7", "stop production autonomy 24x7")),
            ("b79_pause", ("wstrzymaj produkcyjną autonomię 24/7", "wstrzymaj produkcyjna autonomie 24/7")),
            ("b79_resume", ("wznów produkcyjną autonomię 24/7", "wznow produkcyjna autonomie 24/7")),
            ("b79_cycle", ("cykl produkcyjnej autonomii", "run production autonomy cycle")),
            ("b79_report", ("raport dzienny autonomii",)),
            ("b79_history", ("historia produkcyjnej autonomii",)),
            ("b79_status", ("status produkcyjnej autonomii", "status autonomii produkcyjnej", "status b79", "production autonomy status")),
            ("b81_snapshot", ("utwórz profil organizacji", "utworz profil organizacji", "create organization profile")),
            ("b81_export", ("eksportuj profil organizacji", "export organization profile")),
            ("b81_status", ("status profili organizacji", "pokaż profile organizacji", "pokaz profile organizacji", "status b81", "organization profiles status")),
            ("b82_trial", ("uruchom trial licencji", "uruchom trial 14 dni", "start business license trial")),
            ("b82_request", ("eksportuj wniosek aktywacyjny", "export license activation request")),
            ("b82_deactivate", ("dezaktywuj licencję business", "dezaktywuj licencje business")),
            ("b82_status", ("status platformy licencyjnej", "status licencji b82", "status b82", "business license platform status")),
            ("b83_owner", ("ustaw rolę owner", "ustaw role owner")),
            ("b83_admin", ("ustaw rolę admin", "ustaw role admin")),
            ("b83_operator", ("ustaw rolę operator", "ustaw role operator")),
            ("b83_auditor", ("ustaw rolę auditor", "ustaw role auditor")),
            ("b83_status", ("status ról i uprawnień", "status rol i uprawnien", "status kontroli dostępu", "status kontroli dostepu", "status b83", "business access control status")),
            ("b81_b83_status", ("status platformy biznesowej", "status b81-b83", "business platform status")),
            ("b84_export", ("eksportuj raport audytu", "export audit report")),
            ("b84_status", ("status centrum audytu", "status audytu biznesowego", "status b84", "business audit center status")),
            ("b85_create", ("utwórz checkpoint business edition", "utworz checkpoint business edition", "create business checkpoint")),
            ("b85_verify", ("zweryfikuj ostatni checkpoint",)),
            ("b85_restore", ("przygotuj pakiet przywracania", "export restore package")),
            ("b85_status", ("status disaster recovery", "status checkpointów", "status checkpointow", "status b85", "business disaster recovery status")),
            ("b86_stage", ("przygotuj aktualizację business edition", "przygotuj aktualizacje business edition", "stage business update")),
            ("b86_installer", ("eksportuj instalator aktualizacji", "export update installer")),
            ("b86_scan", ("skanuj pakiety aktualizacji",)),
            ("b86_status", ("status centrum aktualizacji", "status b86", "business update center status")),
            ("b84_b86_status", ("status operacji biznesowych", "status b84-b86", "business operations status")),
            ("b87_b88_status", ("status wdrożenia business", "status b87-b88", "business release status")),
            ("b87_first_run", ("inicjalizuj pierwsze uruchomienie business edition", "initialize business first run")),
            ("b87_setup", ("eksportuj instalator business edition", "export business setup package")),
            ("b87_uninstaller", ("eksportuj bezpieczny deinstalator", "export safe business uninstaller")),
            ("b87_status", ("status instalatora business edition", "status b87", "business installation manager status")),
            ("b88_export", ("eksportuj release candidate rc1", "eksportuj rc1", "export release candidate")),
            ("b88_verify", ("zweryfikuj release candidate rc1", "verify release candidate")),
            ("b88_status", ("status release candidate rc1", "status rc1", "status b88", "business release candidate status")),
            ("b80_license", ("pokaż licencję business edition", "pokaz licencje business edition", "status licencji business edition", "licencja business edition", "business edition license")),
            ("b80_integrity", ("pokaż integralność business edition", "pokaz integralnosc business edition", "status integralności business edition", "status integralnosci business edition", "integralność business edition", "integralnosc business edition", "business edition integrity")),
            ("b80_config", ("pokaż konfigurację business edition", "pokaz konfiguracje business edition", "konfiguracja business edition", "konfiguracja business", "business edition configuration")),
            ("b80_status", ("status business edition", "status business", "status b80", "business edition status")),
        )
        for action, phrases in checks:
            if any(phrase in normalized for phrase in phrases):
                return action
        value = str(operation).strip().casefold()
        return value if value.startswith(("b7", "b8")) else None

    @staticmethod
    def _target(suite: Any, action: str) -> tuple[Any, str]:
        mapping = {
            "b71_execute": (getattr(suite, "recovery_execution", None), "execute_latest"),
            "b71_verify": (getattr(suite, "recovery_execution", None), "verify_latest"),
            "b71_rollback": (getattr(suite, "recovery_execution", None), "rollback_latest"),
            "b71_status": (getattr(suite, "recovery_execution", None), "status"),
            "b71_history": (getattr(suite, "recovery_execution", None), "history"),
            "b72_cycle": (getattr(suite, "recovery_learning", None), "run_cycle"),
            "b72_start": (getattr(suite, "recovery_learning", None), "start_background"),
            "b72_stop": (getattr(suite, "recovery_learning", None), "stop_background"),
            "b72_pause": (getattr(suite, "recovery_learning", None), "pause"),
            "b72_resume": (getattr(suite, "recovery_learning", None), "resume"),
            "b72_status": (getattr(suite, "recovery_learning", None), "status"),
            "b72_history": (getattr(suite, "recovery_learning", None), "history"),
            "b73_start": (getattr(suite, "control_center", None), "start_safe_supervisors"),
            "b73_stop": (getattr(suite, "control_center", None), "stop_all_supervisors"),
            "b73_pause": (getattr(suite, "control_center", None), "pause_all_supervisors"),
            "b73_resume": (getattr(suite, "control_center", None), "resume_safe_supervisors"),
            "b73_status": (getattr(suite, "control_center", None), "status"),
            "b73_history": (getattr(suite, "control_center", None), "history"),
            "b74_scan": (getattr(suite, "global_watchdog", None), "run_cycle"),
            "b74_start": (getattr(suite, "global_watchdog", None), "start_background"),
            "b74_stop": (getattr(suite, "global_watchdog", None), "stop_background"),
            "b74_pause": (getattr(suite, "global_watchdog", None), "pause"),
            "b74_resume": (getattr(suite, "global_watchdog", None), "resume"),
            "b74_status": (getattr(suite, "global_watchdog", None), "status"),
            "b74_history": (getattr(suite, "global_watchdog", None), "history"),
            "b75_create": (getattr(suite, "safe_deployment", None), "create_candidate"),
            "b75_canary": (getattr(suite, "safe_deployment", None), "start_canary"),
            "b75_promote": (getattr(suite, "safe_deployment", None), "promote_latest"),
            "b75_rollback": (getattr(suite, "safe_deployment", None), "rollback_latest"),
            "b75_status": (getattr(suite, "safe_deployment", None), "status"),
            "b75_history": (getattr(suite, "safe_deployment", None), "history"),
            "b76_create": (getattr(suite, "release_train", None), "create_release_train"),
            "b76_stable": (getattr(suite, "release_train", None), "mark_stable"),
            "b76_status": (getattr(suite, "release_train", None), "status"),
            "b76_history": (getattr(suite, "release_train", None), "history"),
            "b77_capture": (getattr(suite, "development_memory", None), "capture"),
            "b77_status": (getattr(suite, "development_memory", None), "status"),
            "b77_history": (getattr(suite, "development_memory", None), "history"),
            "b78_audit": (getattr(suite, "security_hardening", None), "audit"),
            "b78_harden": (getattr(suite, "security_hardening", None), "apply_safe_hardening"),
            "b78_status": (getattr(suite, "security_hardening", None), "status"),
            "b78_history": (getattr(suite, "security_hardening", None), "history"),
            "b79_start": (getattr(suite, "production_autonomy", None), "start_background"),
            "b79_stop": (getattr(suite, "production_autonomy", None), "stop_background"),
            "b79_pause": (getattr(suite, "production_autonomy", None), "pause"),
            "b79_resume": (getattr(suite, "production_autonomy", None), "resume"),
            "b79_cycle": (getattr(suite, "production_autonomy", None), "run_cycle"),
            "b79_report": (getattr(suite, "production_autonomy", None), "daily_report"),
            "b79_status": (getattr(suite, "production_autonomy", None), "status"),
            "b79_history": (getattr(suite, "production_autonomy", None), "history"),
            "b81_snapshot": (getattr(suite, "business_edition", None), "snapshot_organization_profile"),
            "b81_export": (getattr(suite, "business_edition", None), "export_organization_profile"),
            "b81_status": (getattr(suite, "business_edition", None), "organization_profiles_status"),
            "b82_trial": (getattr(suite, "business_edition", None), "start_license_trial"),
            "b82_request": (getattr(suite, "business_edition", None), "export_license_request"),
            "b82_deactivate": (getattr(suite, "business_edition", None), "deactivate_business_license"),
            "b82_status": (getattr(suite, "business_edition", None), "license_platform_status"),
            "b83_owner": (getattr(suite, "business_edition", None), "set_owner_role"),
            "b83_admin": (getattr(suite, "business_edition", None), "set_admin_role"),
            "b83_operator": (getattr(suite, "business_edition", None), "set_operator_role"),
            "b83_auditor": (getattr(suite, "business_edition", None), "set_auditor_role"),
            "b83_status": (getattr(suite, "business_edition", None), "access_control_status"),
            "b81_b83_status": (getattr(suite, "business_edition", None), "business_platform_status"),
            "b84_export": (getattr(suite, "business_edition", None), "export_audit_report"),
            "b84_status": (getattr(suite, "business_edition", None), "audit_center_status"),
            "b85_create": (getattr(suite, "business_edition", None), "create_business_checkpoint"),
            "b85_verify": (getattr(suite, "business_edition", None), "verify_business_checkpoint"),
            "b85_restore": (getattr(suite, "business_edition", None), "export_restore_package"),
            "b85_status": (getattr(suite, "business_edition", None), "disaster_recovery_status"),
            "b86_stage": (getattr(suite, "business_edition", None), "stage_business_update"),
            "b86_installer": (getattr(suite, "business_edition", None), "export_update_installer"),
            "b86_scan": (getattr(suite, "business_edition", None), "scan_business_updates"),
            "b86_status": (getattr(suite, "business_edition", None), "update_center_status"),
            "b84_b86_status": (getattr(suite, "business_edition", None), "business_operations_status"),
            "b87_first_run": (getattr(suite, "business_edition", None), "initialize_business_first_run"),
            "b87_setup": (getattr(suite, "business_edition", None), "export_business_setup_package"),
            "b87_uninstaller": (getattr(suite, "business_edition", None), "export_business_uninstaller"),
            "b87_status": (getattr(suite, "business_edition", None), "installation_manager_status"),
            "b88_export": (getattr(suite, "business_edition", None), "export_business_release_candidate"),
            "b88_verify": (getattr(suite, "business_edition", None), "verify_business_release_candidate"),
            "b88_status": (getattr(suite, "business_edition", None), "release_candidate_status"),
            "b87_b88_status": (getattr(suite, "business_edition", None), "business_release_status"),
            "b80_status": (getattr(suite, "business_edition", None), "status"),
            "b80_config": (getattr(suite, "business_edition", None), "configuration"),
            "b80_license": (getattr(suite, "business_edition", None), "license_details"),
            "b80_integrity": (getattr(suite, "business_edition", None), "integrity_status"),
        }
        return mapping.get(action, (None, "status"))
