from __future__ import annotations

from app.assistant.deferred_services import deferred_matches
from app.assistant.natural_language import NaturalLanguageService, fold_text


def matches_personal_assistant(command: object) -> bool:
    text = fold_text(command)
    phrases = (
        "ktora jest godzina",
        "jaka jest godzina",
        "podaj godzine",
        "powiedz mi godzine",
        "aktualna godzina",
        "jaka jest data", "podaj date", "podaj dzisiejsza date", "dzisiejsza data", "jaki mamy dzis dzien", "jaki mamy dzisiaj dzien", "jaki dzisiaj jest dzien", "jaki jest dzis dzien", "dzien tygodnia", "data i godzina", "date and time",
        "status komputera", "stan komputera", "obciazenie komputera", "ile mam baterii", "stan baterii", "poziom baterii", "jak dlugo dziala komputer", "czas pracy komputera", "uzycie procesora", "uzycie pamieci ram",
        "pogoda", "pogode", "pogody", "weather", "forecast",
        "co potrafisz",
        "co umiesz",
        "co mozesz zrobic",
        "jakie masz funkcje",
        "pokaz pomoc",
        "pomoc jarvis",
        "jak z ciebie korzystac",
        "przyklady polecen",
        "lista polecen",
        "centrum mozliwosci",
        "pokaz opcje rozmowy",
        "jakie sa opcje rozmowy",
        "jak mozemy rozmawiac",
        "jaki jest tryb rozmowy",
        "jaki tryb rozmowy",
        "jak teraz odpowiadasz",
        "mow krocej",
        "odpowiadaj krotko",
        "tryb rozmowy krotki",
        "mow dokladniej",
        "odpowiadaj dokladniej",
        "tryb rozmowy dokladny",
        "rozmawiaj luzniej",
        "tryb rozmowy luzny",
        "rozmawiaj naturalnie",
        "odpowiadaj normalnie",
        "tryb rozmowy normalny",
        "kontynuuj rozmowe",
        "rozwin to",
        "opowiedz wiecej",
        "powiedz wiecej",
        "wroc do naszego tematu",
        "a dalej",
        "i co dalej",
        "powiedz to prosciej",
        "wyjasnij inaczej",
        "nie o to mi chodzilo",
        "to bylo za dlugie",
        "to bylo za krotkie",
        "podaj przyklad",
        "daj przyklad",
        "sprobuj jeszcze raz",
        "zadaj mi pytanie",
        "rozwin ostatnia odpowiedz",
        "o czym rozmawialismy",
        "przypomnij nasza rozmowe",
        "jaki byl ostatni temat",
        "co ostatnio omawialismy",
        "status asystenta",
        "status b96",
        "status b97",
        "status b98",
        "status b99",
        "status b100",
        "status rozmowy",
        "kontekst rozmowy",
        "status sterowania pulpitem",
        "niezawodne sterowanie",
        "status pamieci projektow",
        "pamiec projektow",
        "zapamietaj projekt",
        "dodaj projekt",
        "ustaw aktywny projekt",
        "przelacz projekt",
        "zapamietaj preferencje",
        "ustaw preferencje",
        "zapamietaj ze",
        "zapamietaj, ze",
        "zapamietaj sobie ze",
        "zapamietaj sobie, ze",
        "pamietaj ze",
        "pamietaj, ze",
        "co o mnie pamietasz",
        "co pamietasz o mnie",
        "co o mnie wiesz",
        "jakie moje informacje pamietasz",
        "jakie moje preferencje pamietasz",
        "zapomnij ze",
        "zapomnij, ze",
        "zapomnij o",
        "usun z pamieci",
        "status glosu",
        "glos 2.0",
        "voice 2.0",
        "status integracji",
        "pokaz integracje",
        "jakie integracje",
        "polaczenia zewnetrzne",
        "status revenuecat",
        "status meta ads",
        "status claude",
        "status cartesia",
        "status elevenlabs",
        "status paper tradingu", "stan paper tradingu", "status tradingu", "gotowosc tradingu", "gotowosc do tradingu", "zabezpieczenia tradingu", "audyt tradingu", "status silnika tradingowego", "status forex", "gotowosc forex", "skaner forex", "status obserwatora forex", "ile obserwacji forex", "postep obserwacji forex", "czy paper gotowy", "czy paper jest gotowy",
        "raport obserwacji forex", "przejrzyj obserwacje forex", "audyt obserwacji forex", "jakosc obserwacji forex",
        "przygotuj portfel v3 shadow", "zainicjalizuj portfel v3 shadow", "utworz pusty portfel v3 shadow", "przygotuj v3 shadow",
        "tryb ciagly glosu",
        "centrum codziennej pracy",
        "status codziennej pracy",
        "utworz zadanie wieloetapowe",
        "rozpocznij zadanie",
        "uruchom zadanie",
        "nastepny krok",
        "wykonano krok",
        "wstrzymaj zadanie",
        "wznow zadanie",
        "anuluj zadanie",
        "dodaj przypomnienie",
        "przypomnij mi",
        "eksportuj raport codziennej pracy",
        "wyczysc kontekst rozmowy",
        "wyczysc historie rozmowy",
        "zapomnij te rozmowe",
        "kontynuuj ostatnie zadanie",
        "jeszcze raz",
        "powtorz",
        "zrob to jeszcze raz",
        "kontynuuj",
        "jedz dalej",
    )
    return (
        any(phrase in text for phrase in phrases)
        or NaturalLanguageService.classify(command) == "contextual_greeting"
        or deferred_matches(command)
    )



__all__ = ["matches_personal_assistant"]
