from __future__ import annotations


_READ_ONLY_LEARNING_PHRASES = (
    "status uczenia",
    "status uczenia autonomicznego",
    "profil uczenia",
    "profil uczenia autonomicznego",
    "wersje profilu uczenia",
    "historia wersji profilu",
    "historia uczenia",
    "historię uczenia",
    "historia uczenia autonomicznego",
    "historię uczenia autonomicznego",
    "wyjaśnij naukę",
    "wyjasnij nauke",
    "wyjaśnij decyzję uczenia",
    "wyjasnij decyzje uczenia",
    "learning status",
    "learning profile",
    "profile versions",
    "learning history",
    "explain learning",
    "status długotrwałej autonomii",
    "status dlugotrwalej autonomii",
    "status nadzorcy autonomii",
    "pokaż status długotrwałej autonomii",
    "pokaz status dlugotrwalej autonomii",
    "pokaż kolejkę autonomii",
    "pokaz kolejke autonomii",
    "kolejka autonomii",
    "kolejkę autonomii",
    "historia długotrwałej autonomii",
    "historia dlugotrwalej autonomii",
    "status zadania długotrwałego",
    "status zadania dlugotrwalego",
    "pokaż status zadania",
    "pokaz status zadania",
    "pokaż wszystkie zadania",
    "pokaz wszystkie zadania",
    "lista zadań autonomii",
    "lista zadan autonomii",
    "long running autonomy status",
    "autonomy supervisor status",
    "long job status",
    "diagnostyka autonomii",
    "diagnostykę autonomii",
    "diagnostyke autonomii",
    "diagnostyka zadania",
    "diagnostykę zadania",
    "diagnostyke zadania",
    "wyjaśnij błąd zadania",
    "wyjasnij blad zadania",
    "raport błędów autonomii",
    "raport bledow autonomii",
    "historia diagnostyki",
    "historia napraw autonomii",
    "autonomous diagnostics",
    "diagnose longrun-",
    "status inteligencji projektu",
    "pokaż status inteligencji projektu",
    "pokaz status inteligencji projektu",
    "backlog rozwoju",
    "pokaż backlog rozwoju",
    "pokaz backlog rozwoju",
    "historia inteligencji projektu",
    "historia rozwoju autonomicznego",
    "status zadania rozwoju",
    "project intelligence status",
    "development backlog",
    "skanuj projekt i zbuduj backlog",
    "przeskanuj projekt i zbuduj backlog",
    "scan project backlog",
    "status samodzielnego rozwoju",
    "pokaż status samodzielnego rozwoju",
    "pokaz status samodzielnego rozwoju",
    "historia samodzielnego rozwoju",
    "pokaż historię samodzielnego rozwoju",
    "pokaz historie samodzielnego rozwoju",
    "self directed development status",
    "self-directed development status",
    "status rozwoju strategicznego",
    "pokaż status rozwoju strategicznego",
    "pokaz status rozwoju strategicznego",
    "roadmapa rozwoju",
    "roadmapę rozwoju",
    "roadmape rozwoju",
    "pokaż roadmapę rozwoju",
    "pokaz roadmape rozwoju",
    "cele strategiczne jarvisa",
    "historia rozwoju strategicznego",
    "status b57",
    "strategic development status",
    "development roadmap",
    "status wykonania strategicznego",
    "pokaż status wykonania strategicznego",
    "pokaz status wykonania strategicznego",
    "historia wykonania strategicznego",
    "pokaż historię wykonania strategicznego",
    "pokaz historie wykonania strategicznego",
    "status b58",
    "strategic execution status",
    "strategic execution history",
    "status portfolio strategicznego",
    "pokaż status portfolio strategicznego",
    "pokaz status portfolio strategicznego",
    "pokaż portfolio strategiczne",
    "pokaz portfolio strategiczne",
    "historia portfolio strategicznego",
    "pokaż historię portfolio strategicznego",
    "pokaz historie portfolio strategicznego",
    "status adaptacji strategicznej",
    "status b59",
    "strategic portfolio status",
    "strategic portfolio history",
    "status samouczenia strategicznego",
    "pokaż status samouczenia strategicznego",
    "pokaz status samouczenia strategicznego",
    "status ewolucji polityki strategicznej",
    "pokaż politykę ewolucji strategicznej",
    "pokaz polityke ewolucji strategicznej",
    "historia ewolucji polityki strategicznej",
    "pokaż historię ewolucji polityki strategicznej",
    "pokaz historie ewolucji polityki strategicznej",
    "wersje polityki strategicznej",
    "pokaż wersje polityki strategicznej",
    "pokaz wersje polityki strategicznej",
    "status b60",
    "strategic policy evolution status",
    "strategic policy evolution history",
    "strategic policy revisions",
    "status walidacji polityki strategicznej",
    "pokaż status walidacji polityki strategicznej",
    "pokaz status walidacji polityki strategicznej",
    "historia walidacji polityki strategicznej",
    "eksperymenty polityki strategicznej",
    "pokaż eksperymenty polityki strategicznej",
    "pokaz eksperymenty polityki strategicznej",
    "status bezpiecznej promocji polityki",
    "status b61",
    "strategic policy validation status",
    "strategic policy validation history",
    "strategic policy experiments",
    "status wdrażania polityki",
    "status wdrazania polityki",
    "historia wdrożeń polityki",
    "historia wdrozen polityki",
    "status zarządzania celami",
    "status zarzadzania celami",
    "historia zarządzania celami",
    "historia zarzadzania celami",
    "status budżetu autonomii",
    "status budzetu autonomii",
    "status zasobów autonomii",
    "status zasobow autonomii",
    "status uczenia przyczynowego",
    "historia uczenia przyczynowego",
    "status wydań autonomicznych",
    "status wydan autonomicznych",
    "historia wydań autonomicznych",
    "historia wydan autonomicznych",
    "status samokonserwacji",
    "historia samokonserwacji",
    "status autonomii 24/7",
    "status autonomii 24x7",
    "historia autonomii 24/7",
    "status b62-b68",
    "status b62-b69",
    "status b62-b70",
    "status centrum incydentów",
    "status centrum incydentow",
    "status incydentów autonomii",
    "status incydentow autonomii",
    "historia incydentów autonomii",
    "historia incydentow autonomii",
    "status b69",
    "status odzyskiwania autonomii",
    "status odzyskiwania jarvisa",
    "status orkiestratora odzyskiwania",
    "historia odzyskiwania autonomii",
    "status b70",
    "autonomous recovery status",
    "autonomous recovery history",
    "status wykonania odzyskiwania",
    "historia wykonania odzyskiwania",
    "status b71",
    "recovery execution status",
    "status uczenia napraw",
    "historia uczenia napraw",
    "status b72",
    "recovery learning status",
    "centrum sterowania autonomią",
    "centrum sterowania autonomia",
    "status centrum sterowania",
    "status b73",
    "status b71-b79",
    "unified autonomy control center",
    "status globalnego watchdoga",
    "historia globalnego watchdoga",
    "status watchdoga autonomii",
    "status b74",
    "global watchdog status",
    "status bezpiecznego wdrożenia",
    "status bezpiecznego wdrozenia",
    "historia bezpiecznych wdrożeń",
    "historia bezpiecznych wdrozen",
    "status b75",
    "safe autonomous deployment status",
    "status menedżera wydań",
    "status menedzera wydan",
    "historia release train",
    "status b76",
    "autonomous release manager status",
    "status pamięci rozwoju",
    "status pamieci rozwoju",
    "historia pamięci rozwoju",
    "historia pamieci rozwoju",
    "status b77",
    "development memory status",
    "status bezpieczeństwa autonomii",
    "status bezpieczenstwa autonomii",
    "historia audytu bezpieczeństwa",
    "historia audytu bezpieczenstwa",
    "status b78",
    "security hardening status",
    "status produkcyjnej autonomii",
    "status autonomii produkcyjnej",
    "raport dzienny autonomii",
    "historia produkcyjnej autonomii",
    "status b79",
    "production autonomy status",
    "status zarządzania autonomią",
    "status zarzadzania autonomia",
    "safe policy deployment status",
    "goal governance status",
    "resource budget status",
    "causal learning status",
    "autonomous release status",
    "self maintenance status",
    "full autonomy 24x7 status",
    "autonomous incident response status",
    "status business edition",
    "status business",
    "status b80",
    "konfiguracja business edition",
    "konfiguracja business",
    "pokaż status business edition",
    "pokaz status business edition",
    "pokaż konfigurację business edition",
    "pokaz konfiguracje business edition",
    "business edition status",
    "business edition configuration",
    "licencja business edition",
    "status licencji business edition",
    "pokaż licencję business edition",
    "pokaz licencje business edition",
    "integralność business edition",
    "integralnosc business edition",
    "status integralności business edition",
    "status integralnosci business edition",
    "pokaż integralność business edition",
    "pokaz integralnosc business edition",
    "business edition license",
    "business edition integrity",

    "status profili organizacji",
    "pokaż profile organizacji",
    "pokaz profile organizacji",
    "status b81",
    "organization profiles status",
    "status platformy licencyjnej",
    "status licencji b82",
    "status b82",
    "business license platform status",
    "status ról i uprawnień",
    "status rol i uprawnien",
    "status kontroli dostępu",
    "status kontroli dostepu",
    "status b83",
    "business access control status",
    "status platformy biznesowej",
    "status b81-b83",
    "business platform status",
    "status centrum audytu", "status audytu biznesowego", "status b84",
    "business audit center status",
    "status disaster recovery", "status checkpointów", "status checkpointow",
    "zweryfikuj ostatni checkpoint", "status b85",
    "business disaster recovery status",
    "status centrum aktualizacji", "skanuj pakiety aktualizacji",
    "status b86", "business update center status",
    "status operacji biznesowych", "status b84-b86",
    "business operations status",
    "status instalatora business edition", "status b87",
    "business installation manager status",
    "status release candidate rc1", "status rc1", "status b88",
    "zweryfikuj release candidate rc1",
    "business release candidate status", "verify release candidate",
    "status wdrożenia business", "status b87-b88",
    "business release status",
    "status produkcji i sprzedaży", "status b89-b95",
    "status wersji produkcyjnej", "status b89",
    "status aktualizacji klientów", "status b90",
    "status licencji komercyjnych", "status b91",
    "status ochrony dystrybucji", "status b92",
    "status paczki klienta", "status b93",
    "status gotowości sprzedażowej", "status b94",
    "status wydania produkcyjnego", "status b95",
)

_MUTATING_LEARNING_PHRASES = (
    "cofnij profil uczenia",
    "przywróć poprzedni profil",
    "przywroc poprzedni profil",
    "aktywuj profil uczenia",
    "aktywuj wersję profilu",
    "aktywuj wersje profilu",
    "włącz automatyczny trening",
    "wlacz automatyczny trening",
    "wyłącz automatyczny trening",
    "wylacz automatyczny trening",
    "włącz automatyczne uczenie",
    "wlacz automatyczne uczenie",
    "wyłącz automatyczne uczenie",
    "wylacz automatyczne uczenie",
    "zastosuj naukę",
    "zastosuj nauke",
    "naucz jarvisa",
    "naucz jarvis-a",
    "rollback learning profile",
    "activate profile version",
    "enable automatic training",
    "disable automatic training",
    "uruchom nadzorcę autonomii",
    "uruchom nadzorce autonomii",
    "zatrzymaj nadzorcę autonomii",
    "zatrzymaj nadzorce autonomii",
    "wstrzymaj nadzorcę autonomii",
    "wstrzymaj nadzorce autonomii",
    "wznów nadzorcę autonomii",
    "wznow nadzorce autonomii",
    "zaplanuj długotrwałą autonomię",
    "zaplanuj dlugotrwala autonomie",
    "wstrzymaj zadanie długotrwałe",
    "wstrzymaj zadanie dlugotrwale",
    "wstrzymaj zadanie longrun-",
    "wznów zadanie długotrwałe",
    "wznow zadanie dlugotrwale",
    "wznów zadanie longrun-",
    "wznow zadanie longrun-",
    "anuluj zadanie długotrwałe",
    "anuluj zadanie dlugotrwale",
    "anuluj zadanie longrun-",
    "wykonaj teraz zadanie długotrwałe",
    "wykonaj teraz zadanie dlugotrwale",
    "wykonaj teraz zadanie longrun-",
    "uruchom teraz zadanie longrun-",
    "usuń zadanie longrun-",
    "usun zadanie longrun-",
    "usuń zakończone zadania",
    "usun zakonczone zadania",
    "wyczyść zakończone zadania",
    "wyczysc zakonczone zadania",
    "odzyskaj przerwane zadania",
    "ustaw limity długiej autonomii",
    "ustaw limity dlugiej autonomii",
    "start autonomy supervisor",
    "stop autonomy supervisor",
    "schedule long running autonomy",
    "clear completed jobs",
    "bezpieczna naprawa zadania",
    "bezpieczną naprawę zadania",
    "bezpieczna naprawe zadania",
    "napraw zadanie longrun-",
    "spróbuj naprawić zadanie",
    "sprobuj naprawic zadanie",
    "safe repair longrun-",
    "wykonaj cykl inteligencji projektu",
    "uruchom autonomiczny rozwój projektu",
    "zatrzymaj autonomiczny rozwój projektu",
    "wstrzymaj autonomiczny rozwój projektu",
    "wznów autonomiczny rozwój projektu",
    "wznow autonomiczny rozwoj projektu",
    "uruchom najlepsze zadanie rozwoju",
    "wykonaj najlepsze zadanie rozwoju",
    "odrzuć zadanie rozwoju",
    "odrzuc zadanie rozwoju",
    "ustaw politykę inteligencji projektu",
    "ustaw polityke inteligencji projektu",
    "start project intelligence",
    "stop project intelligence",
    "dispatch best opportunity",
    "uruchom samodzielny rozwój",
    "uruchom samodzielny rozwoj",
    "zatrzymaj samodzielny rozwój",
    "zatrzymaj samodzielny rozwoj",
    "wstrzymaj samodzielny rozwój",
    "wstrzymaj samodzielny rozwoj",
    "wznów samodzielny rozwój",
    "wznow samodzielny rozwoj",
    "wykonaj cykl samodzielnego rozwoju",
    "ustaw politykę samodzielnego rozwoju",
    "ustaw polityke samodzielnego rozwoju",
    "start self directed development",
    "start self-directed development",
    "stop self directed development",
    "uruchom rozwój strategiczny",
    "uruchom rozwoj strategiczny",
    "zatrzymaj rozwój strategiczny",
    "zatrzymaj rozwoj strategiczny",
    "wstrzymaj rozwój strategiczny",
    "wstrzymaj rozwoj strategiczny",
    "wznów rozwój strategiczny",
    "wznow rozwoj strategiczny",
    "odśwież roadmapę rozwoju",
    "odswiez roadmape rozwoju",
    "wykonaj cykl rozwoju strategicznego",
    "wybierz cel strategiczny",
    "ustaw politykę rozwoju strategicznego",
    "ustaw polityke rozwoju strategicznego",
    "start strategic development",
    "stop strategic development",
    "refresh development roadmap",
    "run strategic development cycle",
    "uruchom wykonanie strategiczne",
    "zatrzymaj wykonanie strategiczne",
    "wstrzymaj wykonanie strategiczne",
    "wznów wykonanie strategiczne",
    "wznow wykonanie strategiczne",
    "synchronizuj wykonanie strategiczne",
    "zsynchronizuj wykonanie strategiczne",
    "wykonaj następne zadanie strategiczne",
    "wykonaj nastepne zadanie strategiczne",
    "ustaw politykę wykonania strategicznego",
    "ustaw polityke wykonania strategicznego",
    "start strategic execution",
    "stop strategic execution",
    "pause strategic execution",
    "resume strategic execution",
    "sync strategic execution",
    "dispatch strategic execution",
    "uruchom adaptację strategiczną",
    "uruchom adaptacje strategiczna",
    "zatrzymaj adaptację strategiczną",
    "zatrzymaj adaptacje strategiczna",
    "wstrzymaj adaptację strategiczną",
    "wstrzymaj adaptacje strategiczna",
    "wznów adaptację strategiczną",
    "wznow adaptacje strategiczna",
    "przelicz portfolio strategiczne",
    "zbalansuj portfolio strategiczne",
    "wybierz następny cel adaptacyjnie",
    "wybierz nastepny cel adaptacyjnie",
    "ustaw politykę portfolio strategicznego",
    "ustaw polityke portfolio strategicznego",
    "start strategic portfolio",
    "stop strategic portfolio",
    "pause strategic portfolio",
    "resume strategic portfolio",
    "rebalance strategic portfolio",
    "recommend strategic portfolio goal",
    "uruchom samouczenie strategiczne",
    "zatrzymaj samouczenie strategiczne",
    "wstrzymaj samouczenie strategiczne",
    "wznów samouczenie strategiczne",
    "wznow samouczenie strategiczne",
    "wykonaj cykl samouczenia strategicznego",
    "przeprowadź cykl samouczenia strategicznego",
    "przeprowadz cykl samouczenia strategicznego",
    "przelicz ewolucję polityki strategicznej",
    "przelicz ewolucje polityki strategicznej",
    "zastosuj proponowaną politykę strategiczną",
    "zastosuj proponowana polityke strategiczna",
    "cofnij politykę strategiczną",
    "cofnij polityke strategiczna",
    "ustaw politykę samouczenia strategicznego",
    "ustaw polityke samouczenia strategicznego",
    "start strategic policy evolution",
    "stop strategic policy evolution",
    "pause strategic policy evolution",
    "resume strategic policy evolution",
    "run strategic policy learning cycle",
    "apply strategic policy proposal",
    "rollback strategic policy",
    "uruchom walidację polityki strategicznej",
    "uruchom walidacje polityki strategicznej",
    "zatrzymaj walidację polityki strategicznej",
    "zatrzymaj walidacje polityki strategicznej",
    "wstrzymaj walidację polityki strategicznej",
    "wstrzymaj walidacje polityki strategicznej",
    "wznów walidację polityki strategicznej",
    "wznow walidacje polityki strategicznej",
    "przeprowadź cykl walidacji polityki strategicznej",
    "przeprowadz cykl walidacji polityki strategicznej",
    "zwaliduj proponowaną politykę strategiczną",
    "zwaliduj proponowana polityke strategiczna",
    "promuj zwalidowaną politykę strategiczną",
    "promuj zwalidowana polityke strategiczna",
    "odrzuć proponowaną politykę strategiczną",
    "odrzuc proponowana polityke strategiczna",
    "ustaw politykę walidacji strategicznej",
    "ustaw polityke walidacji strategicznej",
    "start strategic policy validation",
    "stop strategic policy validation",
    "pause strategic policy validation",
    "resume strategic policy validation",
    "run strategic policy validation cycle",
    "validate strategic policy proposal",
    "promote validated strategic policy",
    "reject strategic policy proposal",
    "przeprowadź cykl wdrożenia polityki",
    "przeprowadz cykl wdrozenia polityki",
    "wycofaj ostatnią politykę",
    "wycofaj ostatnia polityke",
    "przeprowadź audyt celów",
    "przeprowadz audyt celow",
    "zarządzaj celami autonomicznie",
    "zarzadzaj celami autonomicznie",
    "odśwież budżet autonomii",
    "odswiez budzet autonomii",
    "resetuj obwód błędów autonomii",
    "resetuj obwod bledow autonomii",
    "przeprowadź analizę przyczynową",
    "przeprowadz analize przyczynowa",
    "utwórz kandydata wydania",
    "utworz kandydata wydania",
    "aktywuj wydanie autonomiczne",
    "przygotuj rollback wydania",
    "przywróć poprzednie wydanie",
    "przywroc poprzednie wydanie",
    "przeskanuj konserwację projektu",
    "przeskanuj konserwacje projektu",
    "wykonaj bezpieczne sprzątanie",
    "wykonaj bezpieczne sprzatanie",
    "uruchom autonomię 24/7",
    "uruchom autonomie 24/7",
    "uruchom autonomię 24x7",
    "zatrzymaj autonomię 24/7",
    "zatrzymaj autonomie 24/7",
    "wstrzymaj autonomię 24/7",
    "wstrzymaj autonomie 24/7",
    "wznów autonomię 24/7",
    "wznow autonomie 24/7",
    "przeprowadź cykl autonomii 24/7",
    "przeprowadz cykl autonomii 24/7",
    "run safe policy deployment cycle",
    "run goal governance cycle",
    "refresh resource budget",
    "run causal learning cycle",
    "create autonomous release candidate",
    "activate autonomous release",
    "restore previous autonomous release",
    "scan self maintenance",
    "apply safe maintenance cleanup",
    "start full autonomy 24x7",
    "stop full autonomy 24x7",
    "pause full autonomy 24x7",
    "resume full autonomy 24x7",
    "run full autonomy 24x7 cycle",
    "uruchom monitor incydentów",
    "uruchom monitor incydentow",
    "uruchom centrum incydentów",
    "uruchom centrum incydentow",
    "zatrzymaj monitor incydentów",
    "zatrzymaj monitor incydentow",
    "zatrzymaj centrum incydentów",
    "zatrzymaj centrum incydentow",
    "wstrzymaj monitor incydentów",
    "wstrzymaj monitor incydentow",
    "wstrzymaj centrum incydentów",
    "wstrzymaj centrum incydentow",
    "wznów monitor incydentów",
    "wznow monitor incydentow",
    "wznów centrum incydentów",
    "wznow centrum incydentow",
    "przeprowadź skan incydentów",
    "przeprowadz skan incydentow",
    "ogranicz ostatni incydent",
    "zamknij ostatni incydent",
    "start autonomous incident monitor",
    "stop autonomous incident monitor",
    "pause autonomous incident monitor",
    "resume autonomous incident monitor",
    "run autonomous incident scan",
    "contain latest autonomous incident",
    "resolve latest autonomous incident",
    "przygotuj plan odzyskiwania",
    "zbuduj plan odzyskiwania",
    "wykonaj bezpieczne odzyskiwanie",
    "zweryfikuj odzyskiwanie",
    "przeprowadź cykl odzyskiwania",
    "przeprowadz cykl odzyskiwania",
    "uruchom odzyskiwanie autonomii",
    "uruchom autonomiczne odzyskiwanie",
    "uruchom orkiestrator odzyskiwania",
    "uruchom nadzorcę odzyskiwania",
    "uruchom nadzorce odzyskiwania",
    "zatrzymaj odzyskiwanie autonomii",
    "zatrzymaj orkiestrator odzyskiwania",
    "zatrzymaj nadzorcę odzyskiwania",
    "zatrzymaj nadzorce odzyskiwania",
    "wstrzymaj odzyskiwanie autonomii",
    "wstrzymaj orkiestrator odzyskiwania",
    "wznów odzyskiwanie autonomii",
    "wznow odzyskiwanie autonomii",
    "wznów orkiestrator odzyskiwania",
    "wznow orkiestrator odzyskiwania",
    "prepare autonomous recovery plan",
    "execute safe autonomous recovery",
    "verify autonomous recovery",
    "run autonomous recovery cycle",
    "start autonomous recovery supervisor",
    "stop autonomous recovery supervisor",
    "pause autonomous recovery supervisor",
    "resume autonomous recovery supervisor",
    "wykonaj zatwierdzony plan odzyskiwania",
    "zweryfikuj wykonanie odzyskiwania",
    "wycofaj ostatnie wykonanie odzyskiwania",
    "przeprowadź cykl uczenia napraw",
    "przeprowadz cykl uczenia napraw",
    "uruchom uczenie napraw",
    "zatrzymaj uczenie napraw",
    "wstrzymaj uczenie napraw",
    "wznów uczenie napraw",
    "wznow uczenie napraw",
    "uruchom centrum sterowania autonomią",
    "uruchom centrum sterowania autonomia",
    "zatrzymaj centrum sterowania autonomią",
    "zatrzymaj centrum sterowania autonomia",
    "wstrzymaj centrum sterowania autonomią",
    "wstrzymaj centrum sterowania autonomia",
    "wznów centrum sterowania autonomią",
    "wznow centrum sterowania autonomia",
    "uruchom bezpiecznych nadzorców",
    "uruchom bezpiecznych nadzorcow",
    "zatrzymaj wszystkich nadzorców",
    "zatrzymaj wszystkich nadzorcow",
    "wstrzymaj wszystkich nadzorców",
    "wstrzymaj wszystkich nadzorcow",
    "wznów bezpiecznych nadzorców",
    "wznow bezpiecznych nadzorcow",
    "przeprowadź skan watchdoga",
    "przeprowadz skan watchdoga",
    "uruchom globalny watchdog",
    "zatrzymaj globalny watchdog",
    "wstrzymaj globalny watchdog",
    "wznów globalny watchdog",
    "wznow globalny watchdog",
    "utwórz kandydat wdrożenia",
    "utworz kandydat wdrozenia",
    "uruchom canary wdrożenia",
    "uruchom canary wdrozenia",
    "promuj bezpieczne wdrożenie",
    "promuj bezpieczne wdrozenie",
    "wycofaj bezpieczne wdrożenie",
    "wycofaj bezpieczne wdrozenie",
    "utwórz release train",
    "utworz release train",
    "oznacz wydanie jako stabilne",
    "zapisz pamięć rozwoju",
    "zapisz pamiec rozwoju",
    "przeprowadź audyt bezpieczeństwa",
    "przeprowadz audyt bezpieczenstwa",
    "zastosuj bezpieczne utwardzenie",
    "uruchom produkcyjną autonomię 24/7",
    "uruchom produkcyjna autonomie 24/7",
    "zatrzymaj produkcyjną autonomię 24/7",
    "zatrzymaj produkcyjna autonomie 24/7",
    "wstrzymaj produkcyjną autonomię 24/7",
    "wstrzymaj produkcyjna autonomie 24/7",
    "wznów produkcyjną autonomię 24/7",
    "wznow produkcyjna autonomie 24/7",
    "przeprowadź cykl produkcyjnej autonomii",
    "przeprowadz cykl produkcyjnej autonomii",
    "execute approved recovery plan",
    "run recovery learning cycle",
    "start recovery learning",
    "stop recovery learning",
    "start safe autonomy supervisors",
    "stop all autonomy supervisors",
    "run global watchdog scan",
    "start global watchdog",
    "stop global watchdog",
    "create deployment candidate",
    "run deployment canary",
    "promote safe deployment",
    "rollback safe deployment",
    "create release train",
    "mark release stable",
    "capture development memory",
    "run security hardening audit",
    "apply safe security hardening",
    "start production autonomy 24x7",
    "stop production autonomy 24x7",
    "run production autonomy cycle",

    "utwórz profil organizacji",
    "utworz profil organizacji",
    "eksportuj profil organizacji",
    "uruchom trial licencji",
    "uruchom trial 14 dni",
    "eksportuj wniosek aktywacyjny",
    "dezaktywuj licencję business",
    "dezaktywuj licencje business",
    "ustaw rolę owner",
    "ustaw role owner",
    "ustaw rolę admin",
    "ustaw role admin",
    "ustaw rolę operator",
    "ustaw role operator",
    "ustaw rolę auditor",
    "ustaw role auditor",
    "create organization profile",
    "export organization profile",
    "start business license trial",
    "export license activation request",
    "eksportuj raport audytu", "export audit report",
    "utwórz checkpoint business edition", "utworz checkpoint business edition",
    "create business checkpoint",
    "przygotuj pakiet przywracania", "export restore package",
    "przygotuj aktualizację business edition",
    "przygotuj aktualizacje business edition", "stage business update",
    "eksportuj instalator aktualizacji", "export update installer",
    "inicjalizuj pierwsze uruchomienie business edition",
    "eksportuj instalator business edition", "export business setup package",
    "eksportuj bezpieczny deinstalator", "export safe business uninstaller",
    "eksportuj release candidate rc1", "eksportuj rc1",
    "export release candidate",
    "przygotuj wersję produkcyjną", "promuj wersję do kanału pilot",
    "promuj wersję do kanału stable", "skanuj kanały aktualizacji klientów",
    "eksportuj katalog aktualizacji klientów",
    "inicjalizuj wystawcę licencji komercyjnych",
    "wystaw demonstracyjną licencję komercyjną",
    "zweryfikuj licencję komercyjną", "zbuduj manifest dystrybucji",
    "zweryfikuj manifest dystrybucji", "eksportuj paczkę klienta",
    "zweryfikuj paczkę klienta", "eksportuj pakiet sprzedażowy",
    "potwierdź przegląd dokumentów sprzedażowych",
    "eksportuj wydanie produkcyjne", "zweryfikuj wydanie produkcyjne",
)


def normalize_command(command: str) -> str:
    return " ".join(str(command).casefold().split())


def is_read_only_learning_command(command: str) -> bool:
    normalized = normalize_command(command)
    if any(
        phrase in normalized
        for phrase in _MUTATING_LEARNING_PHRASES
    ):
        return False
    return any(
        phrase in normalized
        for phrase in _READ_ONLY_LEARNING_PHRASES
    )


def is_safe_read_only_thought(thought: dict) -> bool:
    if not isinstance(thought, dict):
        return False
    if bool(thought.get("read_only", False)):
        return True
    if thought.get("handler") == "personal_assistant":
        return bool(thought.get("read_only", False))
    if thought.get("handler") != "autonomous_software_engineer":
        return False
    return is_read_only_learning_command(
        str(thought.get("command", ""))
    )


def is_safe_workspace_preparation_thought(thought: dict) -> bool:
    """Allow isolated patch preparation without treating it as a live write."""
    if not isinstance(thought, dict):
        return False
    return (
        bool(thought.get("safe_preparation", False))
        and bool(thought.get("workspace_only", False))
        and not bool(thought.get("project_write", False))
        and str(thought.get("handler", "")).startswith("safe_development_")
    )
